#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.echain.domain
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      update-strategy: NOT_NULL
#      field-strategy: 2
      
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 1
      
      logic-not-delete-value: 0
      ##默认true
      table-underline: true
    
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    ##是否开启缓存
    cache-enabled: false

spring:
   http:
      multipart:
        ####设置单个文件的大小
        maxFileSize: 2Mb
        ####设置总上传的数据大小
        maxRequestSize: 10Mb

   profiles:
      active: dev
   ##redis配置
   redis:
      database: 0
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0  
         timeout: 10000
         
   ##数据源配置     
   datasource:
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: ${mysql.driverClass}
      url: ${mysql.url}
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         idle-timeout: 500000
         max-lifetime: 540000
         connection-timeout: 60000
         connection-test-query: SELECT 1

